/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MasterAssinaturasRouteImport } from './routes/master-assinaturas'
import { Route as MasterClientesRouteImport } from './routes/master-clientes'
import { Route as MasterComercialRouteImport } from './routes/master-comercial'
import { Route as MasterFinanceiroRouteImport } from './routes/master-financeiro'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as VisualDemoRouteImport } from './routes/visual-demo'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as LojaSlugRouteImport } from './routes/loja/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/master-assinaturas',
  path: '/master-assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterClientesRoute = MasterClientesRouteImport.update({
  id: '/master-clientes',
  path: '/master-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterComercialRoute = MasterComercialRouteImport.update({
  id: '/master-comercial',
  path: '/master-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterFinanceiroRoute = MasterFinanceiroRouteImport.update({
  id: '/master-financeiro',
  path: '/master-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualDemoRoute = VisualDemoRouteImport.update({
  id: '/visual-demo',
  path: '/visual-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master': typeof MasterRoute
  '/master-assinaturas': typeof MasterAssinaturasRoute
  '/master-clientes': typeof MasterClientesRoute
  '/master-comercial': typeof MasterComercialRoute
  '/master-financeiro': typeof MasterFinanceiroRoute
  '/painel': typeof PainelRoute
  '/visual-demo': typeof VisualDemoRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/loja/$slug': typeof LojaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/master': typeof MasterRoute
  '/master-assinaturas': typeof MasterAssinaturasRoute
  '/master-clientes': typeof MasterClientesRoute
  '/master-comercial': typeof MasterComercialRoute
  '/master-financeiro': typeof MasterFinanceiroRoute
  '/painel': typeof PainelRoute
  '/visual-demo': typeof VisualDemoRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/loja/$slug': typeof LojaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/master': typeof MasterRoute
  '/master-assinaturas': typeof MasterAssinaturasRoute
  '/master-clientes': typeof MasterClientesRoute
  '/master-comercial': typeof MasterComercialRoute
  '/master-financeiro': typeof MasterFinanceiroRoute
  '/painel': typeof PainelRoute
  '/visual-demo': typeof VisualDemoRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/loja/$slug': typeof LojaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/master'
    | '/master-assinaturas'
    | '/master-clientes'
    | '/master-comercial'
    | '/master-financeiro'
    | '/painel'
    | '/visual-demo'
    | '/admin/pedidos'
    | '/loja/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/master'
    | '/master-assinaturas'
    | '/master-clientes'
    | '/master-comercial'
    | '/master-financeiro'
    | '/painel'
    | '/visual-demo'
    | '/admin/pedidos'
    | '/loja/$slug'
  id:
    | '__root__'
    | '/'
    | '/master'
    | '/master-assinaturas'
    | '/master-clientes'
    | '/master-comercial'
    | '/master-financeiro'
    | '/painel'
    | '/visual-demo'
    | '/admin/pedidos'
    | '/loja/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasterRoute: typeof MasterRoute
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterClientesRoute: typeof MasterClientesRoute
  MasterComercialRoute: typeof MasterComercialRoute
  MasterFinanceiroRoute: typeof MasterFinanceiroRoute
  PainelRoute: typeof PainelRoute
  VisualDemoRoute: typeof VisualDemoRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  LojaSlugRoute: typeof LojaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-assinaturas': {
      id: '/master-assinaturas'
      path: '/master-assinaturas'
      fullPath: '/master-assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-clientes': {
      id: '/master-clientes'
      path: '/master-clientes'
      fullPath: '/master-clientes'
      preLoaderRoute: typeof MasterClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-comercial': {
      id: '/master-comercial'
      path: '/master-comercial'
      fullPath: '/master-comercial'
      preLoaderRoute: typeof MasterComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-financeiro': {
      id: '/master-financeiro'
      path: '/master-financeiro'
      fullPath: '/master-financeiro'
      preLoaderRoute: typeof MasterFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-demo': {
      id: '/visual-demo'
      path: '/visual-demo'
      fullPath: '/visual-demo'
      preLoaderRoute: typeof VisualDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasterRoute: MasterRoute,
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterClientesRoute: MasterClientesRoute,
  MasterComercialRoute: MasterComercialRoute,
  MasterFinanceiroRoute: MasterFinanceiroRoute,
  PainelRoute: PainelRoute,
  VisualDemoRoute: VisualDemoRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  LojaSlugRoute: LojaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
